version: '3.7'

services:

  netflix-eureka-naming-server:
    image: nikhitha/currms-netflix-eureka-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network: