version: '3.7'

services:

 netflix-eureka-naming-server:
  image:  nikhitha/currms-netflix-eureka-naming-server:0.0.1-SNAPSHOT
  hostname: netflix-eureka-naming-server
  ports:
    - "8761:8761"
  networks:
      - currency-network


 currency-exchange-service:
    image: nikhitha/currms-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    links:
      - "netflix-eureka-naming-server:" 
networks:
  currency-network:
 