version: '3.7'

services:

 netflix-eureka-naming-server:
  image:  nikhitha/currms-netflix-eureka-naming-server:0.0.1-SNAPSHOT
  hostname: discovery
  ports:
    - "8761:8761"


 currency-exchange-service:
    image: nikhitha/currms-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    links:
      - discovery
    

 

 